M48
; DRILL file {KiCad 9.0.6-1.fc42} date 2025-11-29T12:02:29+1030
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-29T12:02:29+10:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-1.fc42
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.500
%
G90
G05
T2
X8.45Y16.2
T3
X26.5Y3.9
T4
X26.5Y6.4
T1
G00X8.45Y4.3
M15
G01X8.45Y3.3
M16
G05
M30
